### ISSUE TITLE
define footer links

### ISSUE THREAD

**Issue by GrantPax** [osgi/osgi.enroute.site#10]
As mentioned in #9, Contacts gives a 404 and the other two links go nowhere.

**Comment by pkriens** [comment]
Can you just create a pull-request with these issues? Then I can immediately integrate or edit them

**Comment by GrantPax** [comment]
I would have already done that if I knew where the footer links should point. I don’t know how you want the “Contact" page to look or what information it should contain. Where would a "Developer" link point? What about “More”? If you’d like to describe what you want for these links, I guess I can take a shot at creating the pages or simply completing the href tags.
