### ISSUE TITLE
Quick Start tutorial should be updated for new Eclipse workflows

### ISSUE THREAD

**Issue by MrSlinkyman** [osgi/osgi.enroute.site#101]
The Quick Start tutorial is very good, very followable, but it is showing its age with respect to the version of eclipse and new workflows for eclipse and bndtools.
Specifically in /qs/300-application.html the instructions specify that after the user selects the create project with "Bndtools OSGi Project" the wizard will open before the template selection.  The order is actually opposite, the template selection comes before the project configuration.  I'm using Eclipse Neon (4.6.0) with bndtools 3.2.0.201605172024.
There are other areas where the eclipse screens don't quite match up with the instructions as well, but this one was the most obvious.

**Comment by pkriens** [comment]
It is almost impossible to keep this 100% correct, but the order was wrong, we changed that in Bndtools 3.2 and I had not updated it.

If you see small updates, just provide a PR on Github, even if it is just a comment in the text. See https://github.com/osgi/osgi.enroute.site/tree/gh-pages/_qs <https://github.com/osgi/osgi.enroute.site/tree/gh-pages/_qs> (You can make a PR completely in the browser.)

Kind regards,

	Peter Kriens
