### ISSUE TITLE
Maven tutorial - bndrun project can be POM project

### ISSUE THREAD

**Issue by azzazzel** [osgi/osgi.enroute.site#106]
"OSGi Runtime" section suggests to create `<packaging>jar</packaging>` maven module for "bndrun". While this is not a problem, it is not strictly needed. The project could be `<packaging>pom</packaging>`. 

It makes no difference if everything is created by hand (like the tutorial does), but when using tools/IDEs to generate the maven module, "jar" results in generating files and folders that are not needed.

**Comment by pkriens** [comment]
True for now. However, I disagree how the current bnd export plugin works and I'd like to change it to make the resulting jar. So I'd like to keep it.
