### ISSUE TITLE
Error in Base Tutorial

### ISSUE THREAD

**Issue by boasdi** [osgi/osgi.enroute.site#131]
Hello,

While doing the Base Tutorial I ran into a problem. In the section 'Dependencies', when adding 'parsii.*' to the 'Private-Package:' section in the source of the bnd.bnd file I get the following error:

Unable to resolve <<INITIAL>> version=null:
   missing requirement osgi.enroute.base.tut.eval.provider 
->  Unable to resolve osgi.enroute.base.tut.eval.provider version=1.0.0.201706120807:
   missing requirement parsii.tokenizer]

Also, on the same page. before there is the following advice:

"BUG: Unfortunately the refresh has a bug. To see the dependency, you must for now
make small change to the build.bnd file in cnf project. This will kick the repository to properly refresh itself."

What is this small change?

Thanks!

**Comment by rotty3000** [comment]
I think Peter meant a literal change something like: "make any kind of small editorial change to the file, such as adding a blank like and then save the file in order to trigger a reload".

**Comment by boasdi** [comment]
I just tried it again and now it worked! Strange, as I had already tried
it and also had clicked on the refresh button for the local repositories.

Thank you!
