### ISSUE TITLE
Enhancing the current contributing guidelines

### ISSUE THREAD

**Issue by Sandared** [osgi/osgi.enroute.site#133]
Hi,

I've worked through the [contributing guidelines](https://github.com/osgi/osgi.enroute.site/blob/gh-pages/CONTRIBUTING.md) and (at least as a Win10 user) struggled when trying to set up everything in order to be able to build the website locally. 

I've written down the steps taken by me to make it work and would be pleased to contribute these notes as an enhanced version of the current contributing guidelines. 

I think that a more detailed set of step-by-step instructions will also lower the initial hurdles for other future contributors :)
 
Kind regards,
Thomas

**Comment by bjhargrave** [comment]
So do you plan on making a PR so we can review your proposed changes?

**Comment by Sandared** [comment]
I'll make a PR in the coming days.
