### ISSUE TITLE
tutorial: won't users have to remove osgi/workspace as a remote?

### ISSUE THREAD

**Issue by GrantPax** [osgi/osgi.enroute.site#14]
In my current understanding of git, cloning the workspace repository maintains the GitHub workspace as a remote. If I have to push my project work to my own remote, don't I have to remove the GitHub workspace as a remote? Maybe I don't understand git. Is there some way in git to section a repository to push/pull to/from different remotes? What if the osgi/workspace changes? Should those changes always be pulled?

**Comment by bjhargrave** [comment]
See the docs for the git remote command to delete the remote for osgi/workspace and add a new remote.

**Comment by GrantPax** [comment]
Right. My question wasn’t clear - it’s about the tutorial content. I’ll just add a sentence about removing the remote. I didn’t know if the remote needed to be left in place for some reason.

**Comment by bjhargrave** [comment]
I guess you should have phrased the issue more as a statement about the change you think is needed rather than as something that just seemed like a question.

**Comment by GrantPax** [comment]
Yeah. Sorry. May my confidence grow with my skills and understanding. Maybe that’s my real contribution: if I can figure out enRoute, anyone can.
