### ISSUE TITLE
Error installing Jekyll on Linux (Mint)

### ISSUE THREAD

**Issue by jrao** [osgi/osgi.enroute.site#142]
Error installing Jekyll on Linux (Mint), following the instructions in `CONTRIBUTING.md`.

After running `bundle exec jekyll build`, this error occurs:

```
	ERROR:  Error installing jekyll:
		ERROR: Failed to build gem native extension.

		current directory: /var/lib/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
	/usr/bin/ruby2.3 -r ./siteconf20171117-322-1cr2dl9.rb extconf.rb
	mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

	extconf failed, exit code 1
```

The solution is to install the ruby-dev package: `sudo apt-get install ruby-dev`

**Comment by axtmann** [comment]
If you run in further problems, ensure, that zlib1g-dev is installed too.
