### ISSUE TITLE
Image links are broken

### ISSUE THREAD

**Issue by nikhilbchilwant** [osgi/osgi.enroute.site#148]
[org.osgi.service.remoteserviceadmin](https://github.com/osgi/osgi.enroute.site/blob/gh-pages/_services/org.osgi.service.remoteserviceadmin.md) page has broken links. They point to RSA-1.png, RSA-2.png, and RSA-3.png. None of them are present in the repo.

**Comment by timothyjward** [comment]
Thank you for taking the time to raise a bug.

As I'm sure you can see the enRoute site has been undergoing some pretty significant changes, and the page you're referring to no longer exists on this site.
