### ISSUE TITLE
marketing: roadmap

### ISSUE THREAD

**Issue by GrantPax** [osgi/osgi.enroute.site#15]
The first two columns on the home page (front.html) spell increased risk.

* First column: OSGi is too complicated and enRoute is the answer.
* Second column: enRoute won't be done for "some time", what is already done is undefined and the balance speaks of plans only.

Presumably, the user is looking to enRoute to help solve OSGi complexity issues. It is entirely unclear how, right now or when, enRoute can do so.

Recommendation: a roadmap that shows where enRoute is now and where it will be and when. This helps users decide if he, she or they can become involved now or later.

**Comment by jconlon** [comment]
I agree.  Interesting functionality,  but does this project have a future?
