### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kevintboyle** [osgi/osgi.enroute.site#164]
![image](https://user-images.githubusercontent.com/3390765/39158511-7f14e068-472e-11e8-9e03-87801b440cdc.png)

The link to the  enRoute Archetypes is broken on the Microservices page.

![image](https://user-images.githubusercontent.com/3390765/39158546-b4ca3faa-472e-11e8-805f-8c88cfa59c0a.png)

**Comment by timothyjward** [comment]
Thanks for letting us know
