### ISSUE TITLE
Configurator Key ":configurator:symbolicname" vs ":configurator:symbolic-name"

### ISSUE THREAD

**Issue by stbischof** [osgi/osgi.enroute.site#170]
Hi,

in the configuration.json at the microservice page, you use the key
:configurator:symbolicname

It should be 
:configurator:symbolic-name

https://enroute.osgi.org/tutorial/030-tutorial_microservice.html

More Information here:

https://issues.apache.org/jira/browse/FELIX-5846?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by timothyjward** [comment]
This example code is actually taken directly from [osgi.enroute](https://github.com/osgi.enroute) (it's a submodule of this repo) and needs to be fixed there
