### ISSUE TITLE
Typo on Microservices tutorial (Dao Implementation Section)

### ISSUE THREAD

**Issue by katcaola** [osgi/osgi.enroute.site#196]
The [Dao Implementation section of the Microservices tutorial](https://enroute.osgi.org/tutorial/030-tutorial_microservice.html#the-dao-implementation) says

> In the `microservice` project director now create the `impl` module using the ds-component Archetype:

When it should say

> In the `microservice` project **directory** now create the `impl` module using the ds-component Archetype:

---

I might also wordsmith it a bit so it becomes

> **Now,** in the `microservice` project **directory,** create the `impl` module using the ds-component Archetype:

**Comment by timothyjward** [comment]
That looks good to me - feel free to create a pull request with the changes

**Comment by katcaola** [comment]
Fixed with Commit #199
