### ISSUE TITLE
why not create the api project as desired instead of immediately changing the name?

### ISSUE THREAD

**Issue by GrantPax** [osgi/osgi.enroute.site#30]
I'm missing something structurally important. From [here](http://enroute.osgi.org/qs/410-exercise-service.html):

### Create an API

In general, you want to have an API project per workspace. So we should create such an API project. In OSGi enRoute this means the name of the project should end with `.api` and you should select the OSGi enRoute template. Let’s to call our API project `com.acme.prime.api`.

In this new project, we rename the template API to reflect our semantics. So rename the `com.acme.prime.api` package to `com.acme.prime.upper.api` and the `Prime.java` file to `Upper.java`.

**Comment by jconlon** [comment]
I had the same question.  But could it be so that if there are other apis that need to be added like lower, than these can be added to the project as well?
