### ISSUE TITLE
Unambiguous use of build and debug configuration.

### ISSUE THREAD

**Issue by groenda** [osgi/osgi.enroute.site#57]
The two run configuration files (bndrun) are confusing if you start with enRoute because each one has a Run OSGi and Debug OSGi button on the top right. The sole purpose/difference i know of for the debug bndrun file is that it allows to add requirements for debugging.

I suggest to merge the bndruns into one to make it straigth forward. Just add a box for 'Debug Requirements' similar to 'Run Requirements'. This can contain all requirements, which are added for debug runs.

**Comment by pkriens** [comment]
It is a bit more complicated than that. The way the debug.bndrun is extended is an enRoute facility using the Bndtools possibilities. I am moving this to Bndtools so we can discuss it there.

**Comment by groenda** [comment]
Can you provide a link to the created Bndtools issue?

**Comment by pkriens** [comment]
https://github.com/bndtools/bndtools/issues/1211
