### ISSUE TITLE
Simplify resolution of requirements to bundles.

### ISSUE THREAD

**Issue by groenda** [osgi/osgi.enroute.site#58]
The resolution procedure is cumbersome in the tutorials. There might be use cases that need to specify run bundles explicitly but the additional `Resolve` step is odd in the tutorials. I'm not sure where the resolve button could actually pay off.

1) `Auto-resolve on save` is not marked by default. This leads to the cumbersome behaviour that you first save, then resolve, then have to see that the file was automatically modified in the background, and then can really save before running the configuration.

2) `Resolve` button could automatically save the file if the file was not dirty before.

**Comment by pkriens** [comment]
Though I think we can make improvements, and I share the feeling that it sometimes is cumbersome, I respectfully disagree that it should be automatic. Automatically resolving is a highly sensitive process. This is why I -never- use auto resolve myself.

Make the Resolve button auto save on a success sounds like a good idea. We'll discuss it in the Bndtools list.(I therefore close it here)

**Comment by groenda** [comment]
If Bndtools support user telemetry it could be interesting on looking on the number of run conconfigurations where its enabled or not. This should give a good feeling for the better default behaviour.

**Comment by groenda** [comment]
Can you provide a link to the issue at Bndtools? Thx.

**Comment by pkriens** [comment]
https://github.com/bndtools/bndtools/issues/1210
