### ISSUE TITLE
'bundle exec jekyll server -w -s _source -d _site' does not work for ruby 2.2.0

### ISSUE THREAD

**Issue by GrantPax** [osgi/osgi.enroute.site#8]
I tried 2.2.0 and it failed. 2.1.4 works. 

$ rvm use 2.2.0
Using /usr/local/rvm/gems/ruby-2.2.0
$  bundle exec jekyll server -w -s _source -d _site
/usr/local/rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.0/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/jekyll-2.0.3/lib/jekyll.rb:21:in `require'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/jekyll-2.0.3/lib/jekyll.rb:21:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/jekyll-2.0.3/bin/jekyll:6:in `require'
	from /usr/local/rvm/gems/ruby-2.2.0/gems/jekyll-2.0.3/bin/jekyll:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
$ rvm use 2.1.4
Using /usr/local/rvm/gems/ruby-2.1.4
$  bundle exec jekyll server -w -s _source -d _site
Configuration file: _source/_config.yml
            Source: _source
       Destination: _site
      Generating... 
                    done.
 Auto-regeneration: enabled
Configuration file: _source/_config.yml
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.

**Comment by GrantPax** [comment]
It's a known (at least debated) issue with ruby. I'd be happy to add a "recommended version" statement to README.md if that would help. Could it be specific to Mac (my platform)? I don't know.

**Comment by bjhargrave** [comment]
This seems like a jekyll dependency. We really need to move this over to the normal GitHub Pages flow. We went the current route because @pkriens needed jekyll 2 features and, at the time, GitHub Pages only used jekyll 1.

**Comment by GrantPax** [comment]
Let me know if I can help?

**Comment by bjhargrave** [comment]
> Let me know if I can help?

Well if you have any skills with GitHub Pages, please take a crack at converting this away from the current model where we build on travis and push to built pages back to the vanilla GitHub Pages model. I tried once on https://github.com/bndtools/bnd.manual which uses the same build but my fu was not enough.

**Comment by bjhargrave** [comment]
> I tried 2.2.0 and it failed. 2.1.4 works.

See https://github.com/osgi/osgi.enroute.site/blob/master/.travis.yml#L3 which declares 2.0 as the required ruby to build the site.

**Comment by GrantPax** [comment]
I didn't know to look at the travis.yml file. Sorry.

I am fu-less on GitHub pages. I'll see what I can do.

**Comment by GrantPax** [comment]
I'll report back on my progress tomorrow unless you need to hear sooner.

**Comment by bjhargrave** [comment]
No rush. @pkriens and I will be at OSGi meetings next week anyway. So we probably will have little spare time...

**Comment by GrantPax** [comment]
I have spent hours on this one hoping to knock it out. I used the [Gemfile from jekyll](http://jekyllrb.com/docs/github-pages/) that is designed to install exactly what Github specifies. Fresh jekyll project (`jekyll new .`). I added or changed nothing myself and here's what we get (below). Running locally and running on GitHub. I don't see how it can be anything but a Github rendering issue. I'm trying to figure out how to debug their render. Truly fu-less. Here's the [repo](https://github.com/GrantPax/osgi.enroute.site.gh-pages) if you are at all interested.

![screen shot 2015-01-17 at 11 16 16 pm](https://cloud.githubusercontent.com/assets/5502828/5791351/ff48ffd0-9e9e-11e4-8f91-2edaabb1eb4a.png)
![screen shot 2015-01-17 at 11 16 34 pm](https://cloud.githubusercontent.com/assets/5502828/5791352/ff5b0a36-9e9e-11e4-8fe1-3d0d931ad18c.png)

**Comment by GrantPax** [comment]
resetting the branch didn't help - same result
`checkout gh-pages ; git push origin --delete gh-pages ; git push origin`

**Comment by GrantPax** [comment]
I'm looking for a snipe

**Comment by GrantPax** [comment]
I've opened an issue with the pages guys. https://github.com/github/pages-gem/issues/114. I'm packing it in for the night.

**Comment by GrantPax** [comment]
OK. The pages guys found the issue. I now get consistent results from a fresh Jekyll install. I am testing basic edits.

What seems to make sense to me is to incrementally add the osgi.enroute.site content to this working repo, testing all the way up. I'm not sure what to do once I get it all working. I guess we'll see when I get there. Please stop me if I should head another way.

**Comment by pkriens** [comment]
Ehhh. Since Github pages did not support Jekyll 2.+ at the time I could not use Github page as is. I just installed Jekyll 2.<latest>from their site and that worked fine. Remember that all those bundles and gem files were a pain in the ass as well.

Then in the master branch you make changes. If you commit, we build on travis and push gh-pages which are then without any further Jekyll help displayed as html.

To verify locally you use (cwd = root of master branch)

   jekyll server -w -s _source -d _site

Post 4000 then on localhost shows you the local mapping.

**Comment by GrantPax** [comment]
Yup. I understand that process. BJ was talking about getting out of the Travis build business. I have a repo that GitHub builds consistently and was going to migrate/reconfigure the current content so Travis is out of the loop. Would you like me to work in that direction or leave as is? I have an issue open (https://github.com/GrantPax/osgi.enroute.site.gh-pages/issues/1 <https://github.com/GrantPax/osgi.enroute.site.gh-pages/issues/1>) and was going to document work there. I’ll stop if you’d rather I work somewhere else.

**Comment by bjhargrave** [comment]
I want to pursue using normal github pages. I'll talk with @pkriens this week to make sure he is in agreement.

**Comment by GrantPax** [comment]
Thanks for the feedback. I will proceed until I hear otherwise.

**Comment by GrantPax** [comment]
OK. After some heads down, I have a Travis-less, all-GitHub repo working [here](http://grantpax.github.io/osgi.enroute.site.gh-pages/). Most of the trouble came from pathing issues with a smattering of other stuff. There's more to do (like the ends of the next<-->previous navigation are still broken). I made some notes on the work here: https://github.com/GrantPax/osgi.enroute.site.gh-pages/issues/1. I have created a [few other issues](https://github.com/GrantPax/osgi.enroute.site.gh-pages/issues) that need to be addressed both sooner and later. I will continue that logging process as appropriate.

If you like what you see (so far), we have to decide what's next. I'm not git-smart enough to know how to apply all the changes I made to my from-scratch repo in any automated way. I don't know how important the history is to you. If you really, really need the history, I'll figure out how to fix the existing repo using what I've learned from this process. My only concern there is the threat of enroute.osgi.org being down for one reason or another.

I'll keep cleaning up and continue working through the tutorials and examples, modifying my new repo - unless you tell me to do differently.

**Comment by pkriens** [comment]
I’d rather keep it working as it is. I am using some advanced features of Jekyll and noticed that Github was rather slow in picking it up. Anyway, it works and there is more than enough work on things that don’t work :-)

Kind regards,

	Peter Kriens

**Comment by GrantPax** [comment]
From @pkriens:
>I’d rather keep it working as it is. I am using some advanced features of Jekyll and noticed that Github was rather slow in picking it up. Anyway, it works and there is more than enough work on things that don’t work :-) 

Either way is fine with me. As I said, I have the site working without Travis with the exception of a minor bug or two. I'll probably have those squashed today. I haven't noticed any build lag from GitHub &mdash; and maybe I'm missing something. Again, either way.

I'd hate to be the point of some contention. I'm just looking to be helpful. Please accept my apologies if I somehow messed something up.

**Comment by GrantPax** [comment]
Ok. With no disrespect for Peter's desire to use the current configuration or other innuendo, the migration to a GitHub-only build is complete. I only finished it off because I was almost there by the time Peter voiced a preference to the contrary. The [reconfigured repo](http://grantpax.github.io/osgi.enroute.site.gh-pages/) can be used or not. It's entirely up to you.

I'm off to work on the tutorial.

**Comment by GrantPax** [comment]
Oops. Forgot. If someone does decide to use the GitHub-only version, the necessary configuration is outlined in the CONFIGURATION.md file in the [meta-config branch](https://github.com/GrantPax/osgi.enroute.site.gh-pages/tree/meta-config).

**Comment by bjhargrave** [comment]
Thanks. I talked with Peter and he is ok with proceeding with this but I won't be able to look at your work until next week when I get back from my trip.

**Comment by GrantPax** [comment]
That works. I hope it helps. Until you have a chance to review, I will duplicate my edits to keep the content of both repos in sync in case something doesn’t work out.

I hope your trip is fruitful. Please give Peter my regards.

**Comment by GrantPax** [comment]
Given that all meaningful work has to end up in the `gh-pages` branch, we'll have to decide what to do with the `master` branch. I'd recommend deleting it. Once/If we cutover, we can delete the `meta-config` branch too.

**Comment by bjhargrave** [comment]
I looked at your repo but the changes were too many and I did not see many of them as necessary. For example, you added base_url everywhere which is not needed on the actual website but only due to the way you were testing.

But after looking at your changes, I realized I could easily do the change and preserve the history. So I made commit 32b17a397cb26ce683a17382837a6047931a545f which converted the site over to github pages. It took a few more commits to get the travis as a test builder for PRs working right but all seems good now. 

The main think I learned from your work was the Gemfile. Thanks for finding that. It was the key to making the change easy. The rest was just moving files from _source => / and some other doc and script edits.

**Comment by GrantPax** [comment]
Per the 4th comment on my [initial issue](https://github.com/GrantPax/osgi.enroute.site.gh-pages/issues/1), I simply could not get the GitHub render to work without the base_url. You clearly have fu I don't. The base_url did indeed make for too many changes. For what it's worth, here is the [GitHub pages issue](https://github.com/github/pages-gem/issues/114) where the gh-pages gem guys told me to set the base_url. So much for that. My fu-lessness hasn't changed.

I'm glad the Gemfile helped at least.

**Comment by GrantPax** [comment]
Oh. This is the testing issue to which you were referring: https://github.com/jekyll/jekyll/issues/332

**Comment by bjhargrave** [comment]
You had it set up as a project site rather than a user site which is why you needed the baseurl.

**Comment by GrantPax** [comment]
Education is expensive. Thanks.
