### ISSUE TITLE
Small Document Inconsistency- Implementing the Chat API

### ISSUE THREAD

**Issue by diderotnet** [osgi/osgi.enroute.site#85]
If we create a provider Bndtools project with the OSGi enRoute templates then we get the proper setup. It will creates a project with a Declarative Services component for us. To setup a provider project, make sure the name of the project ends with .provider. In our case we will use the name osgi.enroute.examples.chat.provider for the project.
This gives us a bundle with a component like:
package osgi.enroute.examples.chat.adapter; **<<<<<<<<<<<<<<<<<< Should this be provider**

import org.osgi.service.component.annotations.Component;

@Component(name = "osgi.enroute.examples.chat")
public class ChatImpl {
}

**Comment by pkriens** [comment]
Its a bug! adapter and provider are synonyms
